blank_issues_enabled: false
contact_links:
  - name: ğŸ“– DocumentaciÃ³n de Git
    url: https://git-scm.com/doc
    about: DocumentaciÃ³n oficial de Git
  - name: ğŸ“š GitHub Docs
    url: https://docs.github.com/
    about: DocumentaciÃ³n oficial de GitHub
  - name: ğŸ“ GitHub Skills
    url: https://skills.github.com/
    about: Cursos interactivos de GitHub
